### ISSUE TITLE
Inconsistent Response Formatting

### ISSUE THREAD

**Issue by honmanyau** [freeCodeCamp/2017-new-coder-survey#3]
Hello there!

I came across some inconsistency in the formatting of some responses when I was looking at the clean data.  I was specifically looking at the responses to learning resources (columns 96 to 115) that people find helpful, and found that some of the responses are formatted with additional quotation marks, as ```"1"```, instead of simply ```1```.

For instance, responses that correspond to columns 96 to 115 of the first 5 respondents look like this:

<pre>
1,NA,NA,NA,NA,NA,1,NA,NA,NA,1,NA,NA,NA,NA,NA,NA,NA,1,1
1,NA,NA,<strong>"1"</strong>,NA,NA,1,NA,NA,NA,NA,NA,NA,NA,NA,1,NA,NA,1,1 // Refer to the third entry
1,NA,NA,<strong>"1"</strong>,NA,NA,1,NA,NA,NA,1,NA,NA,NA,NA,NA,NA,1,1,NA // Refer to the fourth entry
NA,NA,NA,NA,NA,1,1,NA,NA,NA,1,NA,NA,NA,NA,1,NA,NA,NA,NA
NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,1,NA,NA,NA,NA
</pre>

I have no experience in this type of data analysis and not sure if this is going to be much of an issue, but I thought I would point it out in case it does affect anyone!

**EDIT**: Many apologies! I made the wrong selection in the code example earlier due to commas, it's been fixed now!

**Comment by erictleung** [comment]
@honmanyau thanks for taking a look at the data so closely. I personally cleaned the data in this repository and may have neglected to fix this one column. I can update my script and properly format these columns. Feel free to post more formatting issues on here as well :+1:

**Comment by honmanyau** [comment]
@erictleung Absolutely no problem! I just happen to stumble upon it! If anything, thank you very much for your cleaning it and making it available in the first place!
